name: Build macOS App

on: [push, workflow_dispatch]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        # 安装完整Qt开发工具链
        brew install qt@5 pkg-config
        # 获取Qt安装路径并配置环境变量
        QT_PATH=$(brew --prefix qt@5)
        echo "QT_PATH=${QT_PATH}" >> $GITHUB_ENV
        echo "${QT_PATH}/bin" >> $GITHUB_PATH
        
        # 链接Qt库
        sudo ln -sf "${QT_PATH}/lib" /usr/local/lib
        sudo ln -sf "${QT_PATH}/bin/qmake" /usr/local/bin/qmake
        
        # 安装Python依赖
        python -m pip install --upgrade pip setuptools wheel
        pip install pyinstaller pyqt5==5.15.7 --verbose --no-build-isolation
    
    - name: Build Application
      run: |
        pyinstaller --noconfirm --clean --windowed --onefile \
          --name "CountdownTimer" \
          --icon "icon.icns" \
          --add-data "icon.icns:." \
          countdown_timer.py
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS-App
        path: |
          dist/CountdownTimer.app
          dist/CountdownTimer